language: cpp
compiler: gcc

addons:
  apt:
    packages:
    - qtdeclarative5-dev
    - qt5-default
    - qtscript5-dev
    - flex
    - bison

script:
- qmake -r
- make
- bin/QtnPEG
- make clean
- qmake Demo.pro
- make
- make clean
- qmake Tests.pro
- make
- bin/QtnPropertyTests
