language: cpp

os:
- linux
- osx

addons:
  apt:
    packages:
    - qtdeclarative5-dev
    - qt5-default
    - qtscript5-dev
    - flex
    - bison
  homebrew:
    packages:
    - qt5
    - flex
    - bison

matrix:
  include:
  - os: linux
  - os: osx

matrix:
  exclude:
  - os: linux
    addons: homebrew
  - os: osx
    addons: apt

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/flex/bin:$PATH"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/bison/bin:$PATH"; fi
- qmake
- make
- bin/QtnPEG
- qmake Demo.pro
- make
- qmake Tests.pro
- make
- bin/QtnPropertyTests
